name: Load Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-load-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        spec:
          - 'cypress/e2e/tests/test_1.cy.js'
          - 'cypress/e2e/tests/test_2.cy.js'
          - 'cypress/e2e/tests/test_3.cy.js'
          - 'cypress/e2e/tests/test_4.cy.js'
          - 'cypress/e2e/tests/test_5.cy.js'
          - 'cypress/e2e/tests/test_6.cy.js'
          - 'cypress/e2e/tests/test_7.cy.js'
          - 'cypress/e2e/tests/test_8.cy.js'
          - 'cypress/e2e/tests/test_9.cy.js'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Cypress
        uses: cypress-io/github-action@v2
        with:
          start: 'npm start'  # Modifică cu comanda necesară pentru a porni aplicația ta
      
      - name: Run Cypress tests for Load
        run: npx cypress run --spec "${{ matrix.spec }}" --record --parallel --group 'Load'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
