name: UP Load Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Calculate number of tests
        id: calculate-tests
        run: |
          NUM_TESTS=$(node calculate-tests.js)
          echo "::set-output name=num_tests::$NUM_TESTS"
        working-directory: path/to/your/project

      - name: Run Cypress tests
        run: |
          NUM_TESTS=${{ steps.calculate-tests.outputs.num_tests }}
          
          for ((i=1; i<=$NUM_TESTS; i++)); do
              echo "Running test $i"
              npx cypress run --spec "cypress/e2e/Tests/test$i.spec.js"
          done
        working-directory: path/to/your/project

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: cypress/videos
        working-directory: path/to/your/project
