name: Load test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        spec_file: [ 'test_1.cy.js', 'test_2.cy.js', 'test_3.cy.js', 'test_4.cy.js', 'test_5.cy.js', 'test_6.cy.js', 'test_7.cy.js', 'test_8.cy.js', 'test_9.cy.js', 'test_10.cy.js', 'test_11.cy.js', 'test_12.cy.js', 'test_13.cy.js' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        shell: pwsh
        run: |
          Get-ChildItem -Path cypress/e2e/tests -Filter *.cy.js | ForEach-Object {
            & "node_modules\.bin\cypress.cmd" run --spec $_.FullName --record --group "E2E Tests - $($_.BaseName)"
          }
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          osName: 'win32'
          osVersion: '10.0.20348'
          browserName: 'Electron'
          browserVersion: '118.0.5993.159'
