name: UP Load
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: List test files
        run: |
          # List all test files in cypress/e2e/tests directory and store them in a variable
          TEST_FILES=$(find cypress/e2e/tests -type f -name "*.js")
          echo "Found the following test files:"
          echo "$TEST_FILES"

      - name: Run Cypress tests
        strategy:
          matrix:
            spec: ${{ split(env.TEST_FILES, '\n') }}
        run: |
          echo "Running Cypress test: $spec"
          npx cypress run --spec "$spec" --browser electron --record --parallel --group "Cypress Tests"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
