name: UP Load Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        testFile: [
          'cypress/integration/test_1.js',
          'cypress/integration/test_2.js',
          'cypress/integration/test_3.js',
          'cypress/integration/test_4.js',
          'cypress/integration/test_5.js',
          'cypress/integration/test_6.js',
          'cypress/integration/test_7.js',
          'cypress/integration/test_8.js',
          'cypress/integration/test_9.js'
        ]
    steps:
      - name: Configure git
        run: git config --global url."https://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@github.com/".insteadOf https://github.com/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Load Tests'
          spec: ${{ matrix.testFile }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
