name: UP Load Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read CSV and generate job matrix
        id: set-matrix
        run: |
          if [ -f fixtures/links.csv ]; then
            links=$(awk -F, 'NR>1 {print $1}' fixtures/links.csv | jq -R -s -c 'split("\n")[:-1]')
            echo "Matrix: $links"
            echo ":
